//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ilen
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialProd
    {
        public int ID { get; set; }
        public int Material { get; set; }
        public System.DateTime TransDate { get; set; }
        public int Count { get; set; }
        public decimal Price { get; set; }
    
        public virtual Warehouse Warehouse { get; set; }
    }
}
